### ISSUE TITLE
Houdini reference?

### ISSUE THREAD

**Issue by savchenko** [IdleChatIRC/IRC#2]
Out of sheer curiosity...
https://github.com/IdleChatIRC/IRC/blob/691ee3a42fb445070070fba8212efe4535a7f411/Services_Alias.mrc#L11-L26

![images](https://user-images.githubusercontent.com/300146/79060508-f4c1d780-7cc4-11ea-9ff7-0c2c706751df.png)

**Comment by radien** [comment]
Don't think so, this is a Remote script for mIRC that allows you to run a command by just typing the alias into the text input bar.

**Comment by savchenko** [comment]
Got it, pure coincidence :)
